
package importservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "addPojo", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddPojo {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTwo", targetNamespace = "http://webservice/", className = "importservice.AddTwo")
    @ResponseWrapper(localName = "addTwoResponse", targetNamespace = "http://webservice/", className = "importservice.AddTwoResponse")
    @Action(input = "http://webservice/addPojo/addTwoRequest", output = "http://webservice/addPojo/addTwoResponse")
    public int addTwo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addThree", targetNamespace = "http://webservice/", className = "importservice.AddThree")
    @ResponseWrapper(localName = "addThreeResponse", targetNamespace = "http://webservice/", className = "importservice.AddThreeResponse")
    @Action(input = "http://webservice/addPojo/addThreeRequest", output = "http://webservice/addPojo/addThreeResponse")
    public int addThree(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
