
package importservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "addPojoService", targetNamespace = "http://webservice/", wsdlLocation = "http://macbook-pro-de-khatir.local:8080/addWS/addPojoService?wsdl")
public class AddPojoService
    extends Service
{

    private final static URL ADDPOJOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDPOJOSERVICE_EXCEPTION;
    private final static QName ADDPOJOSERVICE_QNAME = new QName("http://webservice/", "addPojoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://macbook-pro-de-khatir.local:8080/addWS/addPojoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDPOJOSERVICE_WSDL_LOCATION = url;
        ADDPOJOSERVICE_EXCEPTION = e;
    }

    public AddPojoService() {
        super(__getWsdlLocation(), ADDPOJOSERVICE_QNAME);
    }

    public AddPojoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDPOJOSERVICE_QNAME, features);
    }

    public AddPojoService(URL wsdlLocation) {
        super(wsdlLocation, ADDPOJOSERVICE_QNAME);
    }

    public AddPojoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDPOJOSERVICE_QNAME, features);
    }

    public AddPojoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddPojoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddPojo
     */
    @WebEndpoint(name = "addPojoPort")
    public AddPojo getAddPojoPort() {
        return super.getPort(new QName("http://webservice/", "addPojoPort"), AddPojo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddPojo
     */
    @WebEndpoint(name = "addPojoPort")
    public AddPojo getAddPojoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "addPojoPort"), AddPojo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDPOJOSERVICE_EXCEPTION!= null) {
            throw ADDPOJOSERVICE_EXCEPTION;
        }
        return ADDPOJOSERVICE_WSDL_LOCATION;
    }

}
